server:
  port: 8090

eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8088/oauth/token
      userAuthorizationUri: http://localhost:8088/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:8088/user

spring:
  application:
    name: SecureService